### ISSUE TITLE
Issue creating compartments from examples/oci-open-lz/shared/open_lz_shared_identity.auto.tfvars.json

### ISSUE THREAD

**Issue by chrisdek11** [oracle-quickstart/terraform-oci-open-lz#16]
When running the module I am seeing the following:

$ terraform plan -var-file ./oci-credentials.tfvars.json -var-file ../examples/oci-open-lz/shared/open_lz_shared_identity.auto.tfvars.json -var-file ../examples/oci-open-lz/shared/open_lz_shared_network.auto.tfvars.json -state ../examples/oci-open-lz/shared/terraform.tfstate

Error: Invalid value for input variable
│
│   on identity.tf line 9, in module "cislz_compartments":
│    9:   compartments_configuration = var.compartments_configuration
│
│ The given value is not suitable for
│ module.cislz_compartments.var.compartments_configuration declared at
│ ..\..\terraform-oci-cis-landing-zone-iam\compartments\variables.tf:12,1-38:
│ attribute "compartments": incorrect map element type: attribute "children":
│ incorrect map element type: attribute "children": incorrect map element
│ type: attribute "tag_defaults": incorrect map element type: attribute
│ "tag_id" is required.

**Comment by paalonso** [comment]
Hi!,

Can you share your configuration so we can check if you put any typo?

TIA.

Rgds.

Pablo

**Comment by paalonso** [comment]
Closing issue without response
