### ISSUE TITLE
Optional input file

### ISSUE THREAD

**Issue by ravi-r-agrawal** [oracle-quickstart/terraform-oci-open-lz#3]
Run the Configurations step has given command as

terraform plan \
-var-file ../examples/oci-open-lz/shared/oci-credentials.tfvars.json \
-var-file ../examples/oci-open-lz/shared/open_lz_shared_identity.auto.tfvars.json \
-var-file ../examples/oci-open-lz/shared/open_lz_shared_network.auto.tfvars.json \
-state ../examples/oci-open-lz/shared/terraform.tfstate

but if we don't want to use any component from network side, we should have option not to pass that command line argument.

**Comment by paalonso** [comment]
Hi Ravi!,

Just skip the network json config file and it should work.

Thanks for your feedback!.

Rgds.

Pablo

**Comment by paalonso** [comment]
Closing issue without response
