### ISSUE TITLE
 Error: Iteration over null value

### ISSUE THREAD

**Issue by sagyvm** [oracle-quickstart/terraform-oci-open-lz#47]
Terraform plan for `/examples/oci-open-lz/op01_manage_shared_services` example giving below error:

Error: Iteration over null value
│
│   on .terraform/modules/cislz_groups/groups/main.tf line 24, in locals:
│   24:   users  = { for u in data.oci_identity_users.these.users : u.name => u }
│     ├────────────────
│     │ data.oci_identity_users.these.users is null
│
│ A null value cannot be used as the collection in a 'for' expression.

**Comment by paalonso** [comment]
Hi @sagyvm!,

Can you share your groups_configuration content please?.

Thanks in advance.

Rgds.

Pablo

**Comment by sagyvm** [comment]
Hi @paalonso, At the moment I am using same files from `examples/oci-open-lz/op01_manage_shared_services`. Please refer the same. I do not have any other configuration.

**Comment by paalonso** [comment]
Ok. I'm working in a new version to be released this week. I'll run again the configs from scratch and see if I can reproduce your problem, not seen so far. Will update this issue with the results.

**Comment by sagyvm** [comment]
Steps to reproduce:
1. Run below command from orchestrator directory
`terraform plan -var-file ../examples/oci-open-lz/op01_manage_shared_services/open_lz_shared_identity.auto.tfvars.json -var-file ../examples/oci-open-lz/op01_manage_shared_services/open_lz_shared_network.auto.tfvars.json -state ../examples/oci-open-lz/op01_manage_shared_services/terraform.tfstate`

**Comment by paalonso** [comment]
We've pushed new examples. During the testing we've recreated the environment successfully without getting that issue. I suggest that you retry again.

**Comment by paalonso** [comment]
This was caused by bad user permissions on groups management.

Groups module needs:

Allow group <group> to manage groups in tenancy

https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/tree/main/groups
