### ISSUE TITLE
typo for variables user_ocid & tenancy_ocid

### ISSUE THREAD

**Issue by paolajuarezgomez** [oracle-quickstart/terraform-oci-open-lz#6]
file https://github.com/oracle-quickstart/terraform-oci-open-lz/tree/master/examples/oci-open-lz/shared/oci-credentials.tfvars.json.template

Has this content:

![image](https://github.com/oracle-quickstart/terraform-oci-open-lz/assets/41003502/9a3c22a0-1e1c-4e92-95be-a4bba67b8132)

tenancy_id should be tenancy_ocid
and 
user_id should be user_ocid

Regards,

**Comment by paalonso** [comment]
I'll fix it

**Comment by paalonso** [comment]
Fixed & merged
